# Generated by Django 3.2.8 on 2022-03-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='curent_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='detination_from', to='core.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_to', to='core.destination'),
        ),
    ]
